#!/bin/bash
sleep 2
/usr/local/bin/mein-dj
service pulseaudio restart
sleep 1
nohup /usr/local/bin/playback-capture 0</dev/null 1>/dev/null 2>/dev/null &
nohup /usr/local/bin/mein-dj-dasmixer 0</dev/null 1>/tmp/mein-dj.log 2>/tmp/mein-dj-err.log & #1>/dev/null 2>/dev/null &
