#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import subprocess
import imp
import time

# get the config file
if len(sys.argv) > 1:

	conf = sys.argv[1]
	config = imp.load_source("config", conf)

	# Start joystick keys
	from joystick import JKeys
	j = JKeys(config)
	j.debug = True
	j.run()


	# start application
	if len(sys.argv) > 2:
		print "Starting application"
		print sys.argv[2:]
		sys.exit(subprocess.call(sys.argv[2:]))
	else:
		print "Not starting any application"
		while True:
			time.sleep(1000)

else:
	print "usage: jkeys config.py [application [params]]"
